/* Generated by cast/gen_wrapper */
static void *__handle;
const char *snd_strerror(int errnum)
{
	static const char *(*__f)(int );
	if (!__f)
		__f = dlsym(__handle, "snd_strerror");

	return __f(errnum);
}
int snd_pcm_open(snd_pcm_t *(*pcm), const char *name, snd_pcm_stream_t stream, int mode)
{
	static int (*__f)(snd_pcm_t *(*), const char *, snd_pcm_stream_t , int );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_open");

	return __f(pcm, name, stream, mode);
}
int snd_pcm_close(snd_pcm_t *pcm)
{
	static int (*__f)(snd_pcm_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_close");

	return __f(pcm);
}
int snd_async_add_pcm_handler(snd_async_handler_t *(*handler), snd_pcm_t *pcm, snd_async_callback_t callback, void *private_data)
{
	static int (*__f)(snd_async_handler_t *(*), snd_pcm_t *, snd_async_callback_t , void *);
	if (!__f)
		__f = dlsym(__handle, "snd_async_add_pcm_handler");

	return __f(handler, pcm, callback, private_data);
}
int snd_pcm_hw_params(snd_pcm_t *pcm, snd_pcm_hw_params_t *params)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params");

	return __f(pcm, params);
}
int snd_pcm_sw_params_current(snd_pcm_t *pcm, snd_pcm_sw_params_t *params)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_sw_params_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_sw_params_current");

	return __f(pcm, params);
}
int snd_pcm_sw_params(snd_pcm_t *pcm, snd_pcm_sw_params_t *params)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_sw_params_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_sw_params");

	return __f(pcm, params);
}
int snd_pcm_prepare(snd_pcm_t *pcm)
{
	static int (*__f)(snd_pcm_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_prepare");

	return __f(pcm);
}
int snd_pcm_start(snd_pcm_t *pcm)
{
	static int (*__f)(snd_pcm_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_start");

	return __f(pcm);
}
snd_pcm_sframes_t snd_pcm_avail(snd_pcm_t *pcm)
{
	static snd_pcm_sframes_t (*__f)(snd_pcm_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_avail");

	return __f(pcm);
}
snd_pcm_sframes_t snd_pcm_writei(snd_pcm_t *pcm, const void *buffer, snd_pcm_uframes_t size)
{
	static snd_pcm_sframes_t (*__f)(snd_pcm_t *, const void *, snd_pcm_uframes_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_writei");

	return __f(pcm, buffer, size);
}
snd_pcm_sframes_t snd_pcm_readi(snd_pcm_t *pcm, void *buffer, snd_pcm_uframes_t size)
{
	static snd_pcm_sframes_t (*__f)(snd_pcm_t *, void *, snd_pcm_uframes_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_readi");

	return __f(pcm, buffer, size);
}
int snd_pcm_link(snd_pcm_t *pcm1, snd_pcm_t *pcm2)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_link");

	return __f(pcm1, pcm2);
}
int snd_pcm_hw_params_any(snd_pcm_t *pcm, snd_pcm_hw_params_t *params)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_any");

	return __f(pcm, params);
}
int snd_pcm_hw_params_malloc(snd_pcm_hw_params_t *(*ptr))
{
	static int (*__f)(snd_pcm_hw_params_t *(*));
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_malloc");

	return __f(ptr);
}
void snd_pcm_hw_params_free(snd_pcm_hw_params_t *obj)
{
	static void (*__f)(snd_pcm_hw_params_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_free");

	__f(obj);
}
int snd_pcm_hw_params_set_access(snd_pcm_t *pcm, snd_pcm_hw_params_t *params, snd_pcm_access_t _access)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_access_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_set_access");

	return __f(pcm, params, _access);
}
int snd_pcm_hw_params_set_format(snd_pcm_t *pcm, snd_pcm_hw_params_t *params, snd_pcm_format_t val)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_format_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_set_format");

	return __f(pcm, params, val);
}
int snd_pcm_hw_params_set_channels(snd_pcm_t *pcm, snd_pcm_hw_params_t *params, unsigned int val)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_set_channels");

	return __f(pcm, params, val);
}
int snd_pcm_hw_params_set_rate_near(snd_pcm_t *pcm, snd_pcm_hw_params_t *params, unsigned int *val, int *dir)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_set_rate_near");

	return __f(pcm, params, val, dir);
}
int snd_pcm_hw_params_set_period_size_near(snd_pcm_t *pcm, snd_pcm_hw_params_t *params, snd_pcm_uframes_t *val, int *dir)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_set_period_size_near");

	return __f(pcm, params, val, dir);
}
int snd_pcm_hw_params_set_buffer_size(snd_pcm_t *pcm, snd_pcm_hw_params_t *params, snd_pcm_uframes_t val)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_hw_params_set_buffer_size");

	return __f(pcm, params, val);
}
int snd_pcm_sw_params_malloc(snd_pcm_sw_params_t *(*ptr))
{
	static int (*__f)(snd_pcm_sw_params_t *(*));
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_sw_params_malloc");

	return __f(ptr);
}
void snd_pcm_sw_params_free(snd_pcm_sw_params_t *obj)
{
	static void (*__f)(snd_pcm_sw_params_t *);
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_sw_params_free");

	__f(obj);
}
int snd_pcm_sw_params_set_avail_min(snd_pcm_t *pcm, snd_pcm_sw_params_t *params, snd_pcm_uframes_t val)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_sw_params_set_avail_min");

	return __f(pcm, params, val);
}
int snd_pcm_sw_params_set_start_threshold(snd_pcm_t *pcm, snd_pcm_sw_params_t *params, snd_pcm_uframes_t val)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_sw_params_set_start_threshold");

	return __f(pcm, params, val);
}
int snd_pcm_sw_params_set_stop_threshold(snd_pcm_t *pcm, snd_pcm_sw_params_t *params, snd_pcm_uframes_t val)
{
	static int (*__f)(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t );
	if (!__f)
		__f = dlsym(__handle, "snd_pcm_sw_params_set_stop_threshold");

	return __f(pcm, params, val);
}
