/* Generated by cast/gen_wrapper */
static void *__handle;
XImage *XCreateImage(Display *__a0, Visual *__a1, unsigned int __a2, int __a3, int __a4, char *__a5, unsigned int __a6, unsigned int __a7, int __a8, int __a9)
{
	static XImage *(*__f)(Display *, Visual *, unsigned int , int , int , char *, unsigned int , unsigned int , int , int );
	if (!__f)
		__f = dlsym(__handle, "XCreateImage");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7, __a8, __a9);
}
Display *XOpenDisplay(const char *__a0)
{
	static Display *(*__f)(const char *);
	if (!__f)
		__f = dlsym(__handle, "XOpenDisplay");

	return __f(__a0);
}
Atom XInternAtom(Display *__a0, const char *__a1, int __a2)
{
	static Atom (*__f)(Display *, const char *, int );
	if (!__f)
		__f = dlsym(__handle, "XInternAtom");

	return __f(__a0, __a1, __a2);
}
Colormap XCreateColormap(Display *__a0, Window __a1, Visual *__a2, int __a3)
{
	static Colormap (*__f)(Display *, Window , Visual *, int );
	if (!__f)
		__f = dlsym(__handle, "XCreateColormap");

	return __f(__a0, __a1, __a2, __a3);
}
Cursor XCreatePixmapCursor(Display *__a0, Pixmap __a1, Pixmap __a2, XColor *__a3, XColor *__a4, unsigned int __a5, unsigned int __a6)
{
	static Cursor (*__f)(Display *, Pixmap , Pixmap , XColor *, XColor *, unsigned int , unsigned int );
	if (!__f)
		__f = dlsym(__handle, "XCreatePixmapCursor");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6);
}
GC XCreateGC(Display *__a0, Drawable __a1, unsigned long __a2, XGCValues *__a3)
{
	static GC (*__f)(Display *, Drawable , unsigned long , XGCValues *);
	if (!__f)
		__f = dlsym(__handle, "XCreateGC");

	return __f(__a0, __a1, __a2, __a3);
}
Pixmap XCreatePixmap(Display *__a0, Drawable __a1, unsigned int __a2, unsigned int __a3, unsigned int __a4)
{
	static Pixmap (*__f)(Display *, Drawable , unsigned int , unsigned int , unsigned int );
	if (!__f)
		__f = dlsym(__handle, "XCreatePixmap");

	return __f(__a0, __a1, __a2, __a3, __a4);
}
Pixmap XCreateBitmapFromData(Display *__a0, Drawable __a1, const char *__a2, unsigned int __a3, unsigned int __a4)
{
	static Pixmap (*__f)(Display *, Drawable , const char *, unsigned int , unsigned int );
	if (!__f)
		__f = dlsym(__handle, "XCreateBitmapFromData");

	return __f(__a0, __a1, __a2, __a3, __a4);
}
Window XCreateWindow(Display *__a0, Window __a1, int __a2, int __a3, unsigned int __a4, unsigned int __a5, unsigned int __a6, int __a7, unsigned int __a8, Visual *__a9, unsigned long __a10, XSetWindowAttributes *__a11)
{
	static Window (*__f)(Display *, Window , int , int , unsigned int , unsigned int , unsigned int , int , unsigned int , Visual *, unsigned long , XSetWindowAttributes *);
	if (!__f)
		__f = dlsym(__handle, "XCreateWindow");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7, __a8, __a9, __a10, __a11);
}
KeySym XLookupKeysym(XKeyEvent *__a0, int __a1)
{
	static KeySym (*__f)(XKeyEvent *, int );
	if (!__f)
		__f = dlsym(__handle, "XLookupKeysym");

	return __f(__a0, __a1);
}
Window XRootWindow(Display *__a0, int __a1)
{
	static Window (*__f)(Display *, int );
	if (!__f)
		__f = dlsym(__handle, "XRootWindow");

	return __f(__a0, __a1);
}
int XSetWMProtocols(Display *__a0, Window __a1, Atom *__a2, int __a3)
{
	static int (*__f)(Display *, Window , Atom *, int );
	if (!__f)
		__f = dlsym(__handle, "XSetWMProtocols");

	return __f(__a0, __a1, __a2, __a3);
}
int XChangeProperty(Display *__a0, Window __a1, Atom __a2, Atom __a3, int __a4, int __a5, const unsigned char *__a6, int __a7)
{
	static int (*__f)(Display *, Window , Atom , Atom , int , int , const unsigned char *, int );
	if (!__f)
		__f = dlsym(__handle, "XChangeProperty");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7);
}
int XCloseDisplay(Display *__a0)
{
	static int (*__f)(Display *);
	if (!__f)
		__f = dlsym(__handle, "XCloseDisplay");

	return __f(__a0);
}
int XCopyArea(Display *__a0, Drawable __a1, Drawable __a2, GC __a3, int __a4, int __a5, unsigned int __a6, unsigned int __a7, int __a8, int __a9)
{
	static int (*__f)(Display *, Drawable , Drawable , GC , int , int , unsigned int , unsigned int , int , int );
	if (!__f)
		__f = dlsym(__handle, "XCopyArea");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7, __a8, __a9);
}
int XDefaultScreen(Display *__a0)
{
	static int (*__f)(Display *);
	if (!__f)
		__f = dlsym(__handle, "XDefaultScreen");

	return __f(__a0);
}
int XDefineCursor(Display *__a0, Window __a1, Cursor __a2)
{
	static int (*__f)(Display *, Window , Cursor );
	if (!__f)
		__f = dlsym(__handle, "XDefineCursor");

	return __f(__a0, __a1, __a2);
}
int XDisplayHeight(Display *__a0, int __a1)
{
	static int (*__f)(Display *, int );
	if (!__f)
		__f = dlsym(__handle, "XDisplayHeight");

	return __f(__a0, __a1);
}
int XDisplayWidth(Display *__a0, int __a1)
{
	static int (*__f)(Display *, int );
	if (!__f)
		__f = dlsym(__handle, "XDisplayWidth");

	return __f(__a0, __a1);
}
int XDrawLine(Display *__a0, Drawable __a1, GC __a2, int __a3, int __a4, int __a5, int __a6)
{
	static int (*__f)(Display *, Drawable , GC , int , int , int , int );
	if (!__f)
		__f = dlsym(__handle, "XDrawLine");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6);
}
int XDrawPoint(Display *__a0, Drawable __a1, GC __a2, int __a3, int __a4)
{
	static int (*__f)(Display *, Drawable , GC , int , int );
	if (!__f)
		__f = dlsym(__handle, "XDrawPoint");

	return __f(__a0, __a1, __a2, __a3, __a4);
}
int XFillPolygon(Display *__a0, Drawable __a1, GC __a2, XPoint *__a3, int __a4, int __a5, int __a6)
{
	static int (*__f)(Display *, Drawable , GC , XPoint *, int , int , int );
	if (!__f)
		__f = dlsym(__handle, "XFillPolygon");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6);
}
int XFillRectangle(Display *__a0, Drawable __a1, GC __a2, int __a3, int __a4, unsigned int __a5, unsigned int __a6)
{
	static int (*__f)(Display *, Drawable , GC , int , int , unsigned int , unsigned int );
	if (!__f)
		__f = dlsym(__handle, "XFillRectangle");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6);
}
int XFlush(Display *__a0)
{
	static int (*__f)(Display *);
	if (!__f)
		__f = dlsym(__handle, "XFlush");

	return __f(__a0);
}
int XFree(void *__a0)
{
	static int (*__f)(void *);
	if (!__f)
		__f = dlsym(__handle, "XFree");

	return __f(__a0);
}
int XFreeGC(Display *__a0, GC __a1)
{
	static int (*__f)(Display *, GC );
	if (!__f)
		__f = dlsym(__handle, "XFreeGC");

	return __f(__a0, __a1);
}
int XFreePixmap(Display *__a0, Pixmap __a1)
{
	static int (*__f)(Display *, Pixmap );
	if (!__f)
		__f = dlsym(__handle, "XFreePixmap");

	return __f(__a0, __a1);
}
int XGetWindowAttributes(Display *__a0, Window __a1, XWindowAttributes *__a2)
{
	static int (*__f)(Display *, Window , XWindowAttributes *);
	if (!__f)
		__f = dlsym(__handle, "XGetWindowAttributes");

	return __f(__a0, __a1, __a2);
}
int XGrabKeyboard(Display *__a0, Window __a1, int __a2, int __a3, int __a4, Time __a5)
{
	static int (*__f)(Display *, Window , int , int , int , Time );
	if (!__f)
		__f = dlsym(__handle, "XGrabKeyboard");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5);
}
int XGrabPointer(Display *__a0, Window __a1, int __a2, unsigned int __a3, int __a4, int __a5, Window __a6, Cursor __a7, Time __a8)
{
	static int (*__f)(Display *, Window , int , unsigned int , int , int , Window , Cursor , Time );
	if (!__f)
		__f = dlsym(__handle, "XGrabPointer");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7, __a8);
}
int XMapWindow(Display *__a0, Window __a1)
{
	static int (*__f)(Display *, Window );
	if (!__f)
		__f = dlsym(__handle, "XMapWindow");

	return __f(__a0, __a1);
}
int XNextEvent(Display *__a0, XEvent *__a1)
{
	static int (*__f)(Display *, XEvent *);
	if (!__f)
		__f = dlsym(__handle, "XNextEvent");

	return __f(__a0, __a1);
}
int XPeekEvent(Display *__a0, XEvent *__a1)
{
	static int (*__f)(Display *, XEvent *);
	if (!__f)
		__f = dlsym(__handle, "XPeekEvent");

	return __f(__a0, __a1);
}
int XPending(Display *__a0)
{
	static int (*__f)(Display *);
	if (!__f)
		__f = dlsym(__handle, "XPending");

	return __f(__a0);
}
int XPutImage(Display *__a0, Drawable __a1, GC __a2, XImage *__a3, int __a4, int __a5, int __a6, int __a7, unsigned int __a8, unsigned int __a9)
{
	static int (*__f)(Display *, Drawable , GC , XImage *, int , int , int , int , unsigned int , unsigned int );
	if (!__f)
		__f = dlsym(__handle, "XPutImage");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7, __a8, __a9);
}
int XSelectInput(Display *__a0, Window __a1, long __a2)
{
	static int (*__f)(Display *, Window , long );
	if (!__f)
		__f = dlsym(__handle, "XSelectInput");

	return __f(__a0, __a1, __a2);
}
int XSetForeground(Display *__a0, GC __a1, unsigned long __a2)
{
	static int (*__f)(Display *, GC , unsigned long );
	if (!__f)
		__f = dlsym(__handle, "XSetForeground");

	return __f(__a0, __a1, __a2);
}
int XSetInputFocus(Display *__a0, Window __a1, int __a2, Time __a3)
{
	static int (*__f)(Display *, Window , int , Time );
	if (!__f)
		__f = dlsym(__handle, "XSetInputFocus");

	return __f(__a0, __a1, __a2, __a3);
}
int XSetLineAttributes(Display *__a0, GC __a1, unsigned int __a2, int __a3, int __a4, int __a5)
{
	static int (*__f)(Display *, GC , unsigned int , int , int , int );
	if (!__f)
		__f = dlsym(__handle, "XSetLineAttributes");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5);
}
int XUndefineCursor(Display *__a0, Window __a1)
{
	static int (*__f)(Display *, Window );
	if (!__f)
		__f = dlsym(__handle, "XUndefineCursor");

	return __f(__a0, __a1);
}
int XUngrabKeyboard(Display *__a0, Time __a1)
{
	static int (*__f)(Display *, Time );
	if (!__f)
		__f = dlsym(__handle, "XUngrabKeyboard");

	return __f(__a0, __a1);
}
int XUngrabPointer(Display *__a0, Time __a1)
{
	static int (*__f)(Display *, Time );
	if (!__f)
		__f = dlsym(__handle, "XUngrabPointer");

	return __f(__a0, __a1);
}
int XWarpPointer(Display *__a0, Window __a1, Window __a2, int __a3, int __a4, unsigned int __a5, unsigned int __a6, int __a7, int __a8)
{
	static int (*__f)(Display *, Window , Window , int , int , unsigned int , unsigned int , int , int );
	if (!__f)
		__f = dlsym(__handle, "XWarpPointer");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7, __a8);
}
XIM XOpenIM(Display *__a0, struct _XrmHashBucketRec *__a1, char *__a2, char *__a3)
{
	static XIM (*__f)(Display *, struct _XrmHashBucketRec *, char *, char *);
	if (!__f)
		__f = dlsym(__handle, "XOpenIM");

	return __f(__a0, __a1, __a2, __a3);
}
int XCloseIM(XIM __a0)
{
	static int (*__f)(XIM );
	if (!__f)
		__f = dlsym(__handle, "XCloseIM");

	return __f(__a0);
}
__attribute__((__sentinel__(0))) XIC XCreateIC(XIM __a0, ...)
{
	void *__args = __builtin_apply_args();
	static void *__f;
	if (!__f)
		__f = dlsym(__handle, "XCreateIC");

	void *__res = __builtin_apply(__f, __args, 512);
	__builtin_return(__res);
}
void XDestroyIC(XIC __a0)
{
	static void (*__f)(XIC );
	if (!__f)
		__f = dlsym(__handle, "XDestroyIC");

	__f(__a0);
}
int Xutf8LookupString(XIC __a0, XKeyPressedEvent *__a1, char *__a2, int __a3, KeySym *__a4, int *__a5)
{
	static int (*__f)(XIC , XKeyPressedEvent *, char *, int , KeySym *, int *);
	if (!__f)
		__f = dlsym(__handle, "Xutf8LookupString");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5);
}
XClassHint *XAllocClassHint(void)
{
	static XClassHint *(*__f)(void);
	if (!__f)
		__f = dlsym(__handle, "XAllocClassHint");

	return __f();
}
XSizeHints *XAllocSizeHints(void)
{
	static XSizeHints *(*__f)(void);
	if (!__f)
		__f = dlsym(__handle, "XAllocSizeHints");

	return __f();
}
int XGetClassHint(Display *__a0, Window __a1, XClassHint *__a2)
{
	static int (*__f)(Display *, Window , XClassHint *);
	if (!__f)
		__f = dlsym(__handle, "XGetClassHint");

	return __f(__a0, __a1, __a2);
}
int XSetClassHint(Display *__a0, Window __a1, XClassHint *__a2)
{
	static int (*__f)(Display *, Window , XClassHint *);
	if (!__f)
		__f = dlsym(__handle, "XSetClassHint");

	return __f(__a0, __a1, __a2);
}
int XSetStandardProperties(Display *__a0, Window __a1, const char *__a2, const char *__a3, Pixmap __a4, char *(*__a5), int __a6, XSizeHints *__a7)
{
	static int (*__f)(Display *, Window , const char *, const char *, Pixmap , char *(*), int , XSizeHints *);
	if (!__f)
		__f = dlsym(__handle, "XSetStandardProperties");

	return __f(__a0, __a1, __a2, __a3, __a4, __a5, __a6, __a7);
}
void XSetWMNormalHints(Display *__a0, Window __a1, XSizeHints *__a2)
{
	static void (*__f)(Display *, Window , XSizeHints *);
	if (!__f)
		__f = dlsym(__handle, "XSetWMNormalHints");

	__f(__a0, __a1, __a2);
}
