#include "term.h"
struct Term {
	void (*kbd_cb)(void *, unsigned char scan_code, int is_pressed);
	void *kbd;
};

#if !defined(_WIN32)
// the key parser was almost auto-generated by Google AI mode
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <termios.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <signal.h>

#define KEY_NONE        0x00
#define KEY_ESC         0x01
#define KEY_BACKSPACE   0x0E
#define KEY_TAB         0x0F
#define KEY_ENTER       0x1C
#define KEY_CTRL        0x1D
#define KEY_SHIFT       0x2A
#define KEY_ALT         0x38
#define KEY_SPACE       0x39
#define KEY_CAPSLOCK    0x3A
#define KEY_F1          0x3B
#define KEY_F2          0x3C
#define KEY_F3          0x3D
#define KEY_F4          0x3E
#define KEY_F5          0x3F
#define KEY_F6          0x40
#define KEY_F7          0x41
#define KEY_F8          0x42
#define KEY_F9          0x43
#define KEY_F10         0x44
#define KEY_F11         0x57
#define KEY_F12         0x58
#define KEY_HOME        0x47
#define KEY_UP          0x48
#define KEY_PAGEUP      0x49
#define KEY_LEFT        0x4B
#define KEY_RIGHT       0x4D
#define KEY_END         0x4F
#define KEY_DOWN        0x50
#define KEY_PAGEDOWN    0x51
#define KEY_INSERT      0x52
#define KEY_DELETE      0x53

static const unsigned char ascii_to_scan[2][256] = {
	{
		['0']=0x0B, ['1']=0x02, ['2']=0x03, ['3']=0x04, ['4']=0x05,
		['5']=0x06, ['6']=0x07, ['7']=0x08, ['8']=0x09, ['9']=0x0A,
		['-']=0x0C, ['=']=0x0D, ['\t']=KEY_TAB, ['\r']=KEY_ENTER,
		['\n']=KEY_ENTER, [' ']=KEY_SPACE, [0x7F]=KEY_BACKSPACE,
		['a']=0x1E, ['b']=0x30, ['c']=0x2E, ['d']=0x20, ['e']=0x12,
		['f']=0x21, ['g']=0x22, ['h']=0x23, ['i']=0x17, ['j']=0x24,
		['k']=0x25, ['l']=0x26, ['m']=0x32, ['n']=0x31, ['o']=0x18,
		['p']=0x19, ['q']=0x10, ['r']=0x13, ['s']=0x1F, ['t']=0x14,
		['u']=0x16, ['v']=0x2F, ['w']=0x11, ['x']=0x2D, ['y']=0x15,
		['z']=0x2C,
		['[']=0x1A, [']']=0x1B, [';']=0x27, ['\'']=0x28, ['`']=0x29,
		['\\']=0x2B, [',']=0x33, ['.']=0x34, ['/']=0x35
	},
	{
		[')']=0x0B, ['!']=0x02, ['@']=0x03, ['#']=0x04, ['$']=0x05,
		['%']=0x06, ['^']=0x07, ['&']=0x08, ['*']=0x09, ['(']=0x0A,
		['_']=0x0C, ['+']=0x0D,
		['A']=0x1E, ['B']=0x30, ['C']=0x2E, ['D']=0x20, ['E']=0x12,
		['F']=0x21, ['G']=0x22, ['H']=0x23, ['I']=0x17, ['J']=0x24,
		['K']=0x25, ['L']=0x26, ['M']=0x32, ['N']=0x31, ['O']=0x18,
		['P']=0x19, ['Q']=0x10, ['R']=0x13, ['S']=0x1F, ['T']=0x14,
		['U']=0x16, ['V']=0x2F, ['W']=0x11, ['X']=0x2D, ['Y']=0x15,
		['Z']=0x2C,
		['{']=0x1A, ['}']=0x1B, [':']=0x27, ['"']=0x28, ['~']=0x29,
		['|']=0x2B, ['<']=0x33, ['>']=0x34, ['?']=0x35
	}
};

static void inject_hw_key(Term *s, unsigned char scan_code, int is_pressed)
{
	s->kbd_cb(s->kbd, scan_code, is_pressed);
}

static void inject_key(Term *s, unsigned char mod, unsigned char ch)
{
	int shift = 0;
	unsigned char scan = ascii_to_scan[0][ch];
	if (!scan) {
		scan = ascii_to_scan[1][ch];
		shift = 1;
	}
	if (!scan)
		return;
	if (mod)
		inject_hw_key(s, mod, 1);
	if (shift)
		inject_hw_key(s, KEY_SHIFT, 1);
	inject_hw_key(s, scan, 1);
	inject_hw_key(s, scan, 0);
	if (shift)
		inject_hw_key(s, KEY_SHIFT, 0);
	if (mod)
		inject_hw_key(s, mod, 0);
}

typedef enum {
	STATE_NORMAL,
	STATE_ESC,
	STATE_CSI,
	STATE_SS3,
	STATE_NUM_SEQ
} KeyState;

static KeyState current_state = STATE_NORMAL;
static int num_param = 0;

static void parse_key(Term *s, unsigned char ch)
{
	switch (current_state) {
		case STATE_NORMAL:
			if (ch == 0x1B) {
				current_state = STATE_ESC;
			} else if (ch >= 0x01 && ch <= 0x1A &&
				   ch != 0x09 && ch != 0x0D && ch != 0x0A) {
				unsigned char ch1 = ch + 0x40;
				inject_key(s, KEY_CTRL, ch1);
			} else {
				inject_key(s, 0, ch);
			}
			break;

		case STATE_ESC:
			if (ch == '[') {
				current_state = STATE_CSI;
			} else if (ch == 'O') {
				current_state = STATE_SS3;
			} else {
				inject_key(s, KEY_ALT, ch);
				current_state = STATE_NORMAL;
			}
			break;

		case STATE_CSI:
			if (ch >= 'A' && ch <= 'D') {
				unsigned char d_code = KEY_NONE;
				if (ch == 'A') d_code = KEY_UP;
				else if (ch == 'B') d_code = KEY_DOWN;
				else if (ch == 'C') d_code = KEY_RIGHT;
				else if (ch == 'D') d_code = KEY_LEFT;
				if (d_code != KEY_NONE) {
					inject_hw_key(s, d_code, 1);
					inject_hw_key(s, d_code, 0);
				}
				current_state = STATE_NORMAL;
			} else if (ch >= '0' && ch <= '9') {
				num_param = ch - '0';
				current_state = STATE_NUM_SEQ;
			} else {
				current_state = STATE_NORMAL;
			}
			break;

		case STATE_SS3:
			{
				unsigned char f_code = KEY_NONE;
				if (ch == 'A') f_code = KEY_UP;
				else if (ch == 'B') f_code = KEY_DOWN;
				else if (ch == 'C') f_code = KEY_RIGHT;
				else if (ch == 'D') f_code = KEY_LEFT;
				else if (ch == 'P') f_code = KEY_F1;
				else if (ch == 'Q') f_code = KEY_F2;
				else if (ch == 'R') f_code = KEY_F3;
				else if (ch == 'S') f_code = KEY_F4;
				if (f_code != KEY_NONE) {
					inject_hw_key(s, f_code, 1);
					inject_hw_key(s, f_code, 0);
				}
				current_state = STATE_NORMAL;
			}
			break;

		case STATE_NUM_SEQ:
			if (ch >= '0' && ch <= '9') {
				num_param = (num_param * 10) + (ch - '0');
			} else if (ch == '~') {
				unsigned char ex_code = KEY_NONE;
				switch (num_param) {
					case 1:  ex_code = KEY_HOME; break;
					case 2:  ex_code = KEY_INSERT; break;
					case 3:  ex_code = KEY_DELETE; break;
					case 4:  ex_code = KEY_END; break;
					case 5:  ex_code = KEY_PAGEUP; break;
					case 6:  ex_code = KEY_PAGEDOWN; break;
					case 15: ex_code = KEY_F5; break;
					case 17: ex_code = KEY_F6; break;
					case 18: ex_code = KEY_F7; break;
					case 19: ex_code = KEY_F8; break;
					case 20: ex_code = KEY_F9; break;
					case 21: ex_code = KEY_F10; break;
					case 23: ex_code = KEY_F11; break;
					case 24: ex_code = KEY_F12; break;
				}
				if (ex_code != KEY_NONE) {
					inject_hw_key(s, ex_code, 1);
					inject_hw_key(s, ex_code, 0);
				}
				current_state = STATE_NORMAL;
			} else {
				current_state = STATE_NORMAL;
			}
			break;
	}
}

struct termios orig_termios;

static void sigterm(int _)
{
	exit(1);
}

static void disable_raw_mode()
{
	tcsetattr(STDIN_FILENO, TCSAFLUSH, &orig_termios);
	const static char seq[] = "\x1b[?1l\x1b[?1049l\x1b[?25h";
	write(STDIN_FILENO, seq, strlen(seq));
}

static void enable_raw_mode()
{
	tcgetattr(STDIN_FILENO, &orig_termios);
	atexit(disable_raw_mode);
	struct termios raw = orig_termios;
	raw.c_lflag &= ~(ECHO | ICANON | ISIG);
	raw.c_iflag &= ~(IXON);
	raw.c_cc[VMIN] = 0;
	raw.c_cc[VTIME] = 1;
	signal(SIGTERM, sigterm);

	tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
	const static char seq[] = "\x1b[?1049h\x1b[?1h\x1b[?25h";
	write(STDIN_FILENO, seq, strlen(seq));
}

void term_step(Term *s)
{
	unsigned char ch;
	int avail;
	while (1) {
		ioctl(STDIN_FILENO, FIONREAD, &avail);
		if (avail == 0)
			return;
		if (read(STDIN_FILENO, &ch, 1) != 1)
			abort();
		if (ch == 0x1b) {
			int avail;
			ioctl(STDIN_FILENO, FIONREAD, &avail);
			if (avail == 0) {
				inject_hw_key(s, KEY_ESC, 1);
				inject_hw_key(s, KEY_ESC, 0);
				current_state = STATE_NORMAL;
				return;
			}
		}
		parse_key(s, ch);
	}
}

#include "vga.h"
#define SET_CURSOR(a, b) printf("\033[%d;%dH", a, b)
#define SET_ATTR(a, b) printf("\033[%d;%dm", a, b)
#define FFLUSH() fflush(stdout)

static const int cmap[16] = {
	0, 4, 2, 6, 1, 5, 3, 7, 8, 12, 10, 14, 9, 13, 11, 15
};

static const char *cp437_to_utf8[] = {
	"Ç", "ü", "é", "â", "ä", "à", "å", "ç", // 80-87
	"ê", "ë", "è", "ï", "î", "ì", "Ä", "Å", // 88-8F
	"É", "æ", "Æ", "ô", "ö", "ò", "û", "ù", // 90-97
	"ÿ", "Ö", "Ü", "¢", "£", "¥", "₧", "ƒ", // 98-9F
	"á", "í", "ó", "ú", "ñ", "Ñ", "ª", "º", // A0-A7
	"¿", "⌐", "¬", "½", "¼", "¡", "«", "»", // A8-AF
	"░", "▒", "▓", "│", "┤", "╡", "╢", "╖", // B0-B7
	"╕", "╣", "║", "╗", "╝", "╜", "╛", "┐", // B8-BF
	"└", "┴", "┬", "├", "─", "┼", "╞", "╟", // C0-C7
	"╚", "╔", "╩", "╦", "╠", "═", "╬", "╧", // C8-CF
	"╨", "╤", "╥", "╙", "╘", "╒", "╓", "╫", // D0-D7
	"╪", "┘", "┌", "█", "▄", "▌", "▐", "▀", // D8-DF
	"α", "ß", "Γ", "π", "Σ", "σ", "µ", "τ", // E0-E7
	"Φ", "Θ", "Ω", "δ", "∞", "φ", "ε", "∩", // E8-EF
	"≡", "±", "≥", "≤", "⌠", "⌡", "÷", "≈", // F0-F7
	"°", "∙", "·", "√", "ⁿ", "²", "■", "\xC2\xA0" // F8-FF
};

static void putchar_cp437(unsigned char cp437_char) {
	if (cp437_char < 0x80) {
		putchar(cp437_char);
		return;
	}
	fputs(cp437_to_utf8[cp437_char - 0x80], stdout);
}

static void set_cursor(void *o, int y, int x)
{
	SET_CURSOR(y + 1, x + 1);
	FFLUSH();
}

static void put_char2(void *o, int y, int x, int ch, int t)
{
	int fg = cmap[t & 0xf];
	int bg = cmap[(t >> 4) & 0xf];
	printf("\0337\033[?25l");
	SET_CURSOR(y + 1, x + 1);
	SET_ATTR(fg >= 8 ? 82 + fg : 30 + fg, bg >= 8 ? 92 + bg : 40 + bg);
	putchar_cp437(ch);
	printf("\033[?25h\0338");
	FFLUSH();
}

static void refresh(void *o, const uint8_t *ram, int width, int height)
{
	printf("\0337\033[?25l");
	for (int i = 0; i < height; i++) {
		SET_CURSOR(i + 1, 1);
		for (int j = 0; j < width; j++) {
			uint32_t a1 = i * width + j;
			int t = ram[a1 * 4 + 1];
			int fg = cmap[t & 0xf];
			int bg = cmap[(t >> 4) & 0xf];
			SET_ATTR(fg >= 8 ? 82 + fg : 30 + fg,
				 bg >= 8 ? 92 + bg : 40 + bg);
			putchar_cp437(ram[a1 * 4]);
		}
	}
	printf("\033[?25h\0338");
	FFLUSH();
}

static VGATextOps ops = {
	.set_cursor = set_cursor,
	.put_char2 = put_char2,
	.refresh = refresh,
};

Term *term_init(
	VGAState *vga,
	void (*kbd_cb)(void *, unsigned char scan_code, int is_pressed),
	void *kbd)
{
	Term *s = malloc(sizeof(Term));
	s->kbd_cb = kbd_cb;
	s->kbd = kbd;
	vga_set_text_ops(vga, &ops, NULL);
	enable_raw_mode();
	return s;
}
#else
#include <stdio.h>
#include <stdlib.h>
Term *term_init(
	VGAState *vga,
	void (*kbd_cb)(void *, unsigned char scan_code, int is_pressed),
	void *kbd)
{
	fprintf(stderr, "term: unsupported platform\n");
	exit(1);
}

void term_step(Term *s)
{
}
#endif
