#!/usr/bin/env python3
# Almost auto-generated by Google AI mode, use at your own risk!
#
# trim_fat.py: scans FAT partitions, zero-filling unused clusters and dir entries.
# By zero-filling slack space, the final .img file becomes highly compressible.
#
# Usage: trim_fat.py <file.img>
#
import os

def clean_fat_partition(f, partition_start_sector, bytes_per_sector=512):
    """Processes a single FAT16/FAT32 partition. Throws errors for FAT12, exFAT, or invalid types."""
    partition_offset = partition_start_sector * bytes_per_sector

    # 1. Read BPB (BIOS Parameter Block) parameters
    f.seek(partition_offset + 11)
    bps = int.from_bytes(f.read(2), "little")
    if bps == 0:
        raise ValueError("Invalid sector size (0 bytes per sector). Connection aborted.")

    sectors_per_cluster = int.from_bytes(f.read(1), "little")
    reserved_sectors = int.from_bytes(f.read(2), "little")
    num_fats = int.from_bytes(f.read(1), "little")

    f.seek(partition_offset + 17)
    root_entries = int.from_bytes(f.read(2), "little")

    f.seek(partition_offset + 19)
    total_sectors_16 = int.from_bytes(f.read(2), "little")

    f.seek(partition_offset + 22)
    fat_size_16 = int.from_bytes(f.read(2), "little")

    f.seek(partition_offset + 32)
    total_sectors_32 = int.from_bytes(f.read(4), "little")

    f.seek(partition_offset + 36)
    fat_size_32 = int.from_bytes(f.read(4), "little")

    # 2. Strict Filesystem Type Verification (FAT12 / FAT16 / FAT32 / exFAT)
    f.seek(partition_offset + 3)
    exfat_sig = f.read(8)
    if exfat_sig == b'EXFAT   ':
        raise NotImplementedError("Detected exFAT filesystem. This script does NOT support exFAT. Execution terminated.")

    # Calculate total clusters (Official Microsoft Method)
    fat_size = fat_size_32 if fat_size_16 == 0 else fat_size_16
    total_sectors = total_sectors_16 if total_sectors_16 != 0 else total_sectors_32

    root_size_sectors = ((root_entries * 32) + (bps - 1)) // bps
    data_sectors = total_sectors - (reserved_sectors + (num_fats * fat_size) + root_size_sectors)

    if sectors_per_cluster == 0:
        raise ValueError("Invalid cluster size (0 sectors per cluster). Execution terminated.")

    total_clusters = data_sectors // sectors_per_cluster

    # Determine type based on cluster count limits
    if total_clusters < 4085:
        raise NotImplementedError(f"Detected FAT12 filesystem (Clusters: {total_clusters}). This script does NOT support FAT12. Execution terminated.")
    elif total_clusters < 65525:
        is_fat32 = False
        fs_type_string = "FAT16"
    else:
        is_fat32 = True
        fs_type_string = "FAT32"

    print(f"  -> Filesystem: {fs_type_string}")
    print(f"  -> Cluster Size: {bps * sectors_per_cluster} bytes")

    bytes_per_cluster = bps * sectors_per_cluster
    fat_start = partition_offset + (reserved_sectors * bps)
    fat_bytes_size = fat_size * bps
    root_start = fat_start + (num_fats * fat_bytes_size)
    root_size = root_entries * 32
    data_start = root_start + root_size

    f.seek(partition_offset + 44)
    fat32_root_cluster = int.from_bytes(f.read(4), "little") if is_fat32 else 0

    # =========================================================
    # Read FAT Table for cluster tracking and zero-filling
    # =========================================================
    f.seek(fat_start)
    fat_data = f.read(fat_bytes_size)
    entry_size = 4 if is_fat32 else 2

    def get_cluster_value(c_idx):
        offset = c_idx * entry_size
        if offset + entry_size > len(fat_data): return 0xFFFFFFFF
        val = int.from_bytes(fat_data[offset:offset+entry_size], "little")
        return (val & 0x0FFFFFFF) if is_fat32 else val

    def get_cluster_chain(start_cluster):
        chain = []
        curr = start_cluster
        eof_marker = 0x0FFFFFFF if is_fat32 else 0xFFFF
        while curr >= 2 and curr < (eof_marker - 7):
            if curr in chain: break
            chain.append(curr)
            curr = get_cluster_value(curr)
        return chain

    def get_cluster_offset(cluster_idx):
        return data_start + (cluster_idx - 2) * bytes_per_cluster

    # =========================================================
    # Directory processing logic
    # =========================================================
    removed_e5_count = 0

    def process_directory_data(dir_bytes):
        nonlocal removed_e5_count
        valid_entries = []
        subdirectory_clusters = []
        has_e5 = False

        for i in range(0, len(dir_bytes), 32):
            entry = dir_bytes[i:i+32]
            if len(entry) < 32 or entry == b'\x00' * 32:
                break

            attr = entry[11]
            is_lfn = (attr == 0x0F)

            if entry[0] == 0xE5:
                if not is_lfn:
                    has_e5 = True
                    removed_e5_count += 1
                    continue

            valid_entries.append(entry)

            if (attr & 0x10) and not is_lfn:
                name = entry[0:8].decode('ascii', errors='ignore').strip()
                if name != '.' and name != '..':
                    high_clust = int.from_bytes(entry[20:22], "little") if is_fat32 else 0
                    low_clust = int.from_bytes(entry[26:28], "little")
                    sub_cluster = (high_clust << 16) | low_clust
                    if sub_cluster >= 2:
                        subdirectory_clusters.append(sub_cluster)

        if has_e5:
            new_data = bytearray()
            for entry in valid_entries:
                new_data.extend(entry)
            remaining = len(dir_bytes) - len(new_data)
            if remaining > 0:
                new_data.extend(b'\x00' * remaining)
            return new_data, subdirectory_clusters

        return dir_bytes, subdirectory_clusters

    # =========================================================
    # BFS Directory Tree Traversal
    # =========================================================
    directory_queue = []

    if not is_fat32:
        directory_queue.append(("root_fixed", root_start, root_size))
    else:
        root_chain = get_cluster_chain(fat32_root_cluster)
        directory_queue.append(("sub_or_fat32root", root_chain, 0))

    print("  -> Scanning directory tree recursively...")

    while directory_queue:
        dir_type, target, size = directory_queue.pop(0)

        if dir_type == "root_fixed":
            f.seek(target)
            orig_data = f.read(size)
            new_data, sub_clusters = process_directory_data(orig_data)
            if orig_data != new_data:
                f.seek(target)
                f.write(new_data)
            for sc in sub_clusters:
                directory_queue.append(("sub_or_fat32root", get_cluster_chain(sc), 0))
        else:
            cluster_chain = target
            if not cluster_chain: continue

            combined_dir_data = bytearray()
            for c in cluster_chain:
                f.seek(get_cluster_offset(c))
                combined_dir_data.extend(f.read(bytes_per_cluster))

            new_data, sub_clusters = process_directory_data(combined_dir_data)

            if combined_dir_data != new_data:
                for idx, c in enumerate(cluster_chain):
                    chunk = new_data[idx * bytes_per_cluster : (idx + 1) * bytes_per_cluster]
                    f.seek(get_cluster_offset(c))
                    f.write(chunk)

            for sc in sub_clusters:
                directory_queue.append(("sub_or_fat32root", get_cluster_chain(sc), 0))

    print(f"     [+] Optimized directories, removed {removed_e5_count} E5 entries.")

    # =========================================================
    # Zero-filling unused clusters
    # =========================================================
    f.seek(0, os.SEEK_END)
    img_size = f.tell()

    zero_cluster_count = 0
    blank_cluster_data = b'\x00' * bytes_per_cluster
    total_entries = len(fat_data) // entry_size

    for cluster_idx in range(2, total_entries):
        if get_cluster_value(cluster_idx) == 0:
            cluster_pos = get_cluster_offset(cluster_idx)
            if cluster_pos + bytes_per_cluster <= img_size:
                f.seek(cluster_pos)
                f.write(blank_cluster_data)
                zero_cluster_count += 1

    print(f"     [+] Zero-filled {zero_cluster_count} unused clusters.")


def parse_logical_partitions(f, ext_start_sector, current_ebr_sector, bytes_per_sector=512):
    """Recursively traverses the EBR chain to find all logical partitions."""
    ebr_offset = current_ebr_sector * bytes_per_sector

    f.seek(ebr_offset + 510)
    if f.read(2) != b'\x55\xAA':
        return

    fat_types = [0x01, 0x04, 0x06, 0x0B, 0x0C, 0x0E]

    for i in range(2):
        f.seek(ebr_offset + 446 + (i * 16))
        entry = f.read(16)
        p_type = entry[4]
        if p_type == 0: continue

        start_sector = int.from_bytes(entry[8:12], "little")
        total_sectors = int.from_bytes(entry[12:16], "little")

        if i == 0:
            absolute_start = current_ebr_sector + start_sector
            print(f"\n[Logical Partition] Type: 0x{p_type:02X}, Start Sector: {absolute_start}, Total Sectors: {total_sectors}")

            if p_type in fat_types:
                try:
                    clean_fat_partition(f, absolute_start)
                except (NotImplementedError, ValueError) as e:
                    print(f"  [!] Critical Error: {e}")
                    raise e
            else:
                print("  -> Non-FAT partition, skipping.")

        elif i == 1:
            next_ebr_sector = ext_start_sector + start_sector
            parse_logical_partitions(f, ext_start_sector, next_ebr_sector, bytes_per_sector)


def scan_and_clean_image(img_path):
    print(f"Analyzing disk image: {img_path}")
    if not os.path.exists(img_path):
        print("Error: File does not exist!")
        return

    with open(img_path, "r+b") as f:
        # Check overall signature first
        f.seek(510)
        if f.read(2) != b'\x55\xAA':
            raise ValueError("Invalid image: Missing boot indicator (55AA). Connections aborted.")

        # ---------------------------------------------------------
        # PROBING LOGIC: Check if it is a Floppy/Raw Partition (DBR)
        # ---------------------------------------------------------
        is_raw_partition = False
        try:
            f.seek(11)
            prob_bps = int.from_bytes(f.read(2), "little")
            prob_spc = int.from_bytes(f.read(1), "little")
            prob_res = int.from_bytes(f.read(2), "little")
            prob_fats = int.from_bytes(f.read(1), "little")

            # Standard FAT DBR validations:
            # 1. Sector size must be standard (usually 512)
            # 2. Sectors per cluster must be power of 2 (1, 2, 4, 8, 16, 32, 64, 128)
            # 3. Reserved sectors and Number of FATs cannot be 0
            if (prob_bps in [512, 1024, 2048, 4096] and
                (prob_spc & (prob_spc - 1)) == 0 and prob_spc > 0 and
                prob_res > 0 and prob_fats > 0):

                # Check for exFAT signature just in case
                f.seek(3)
                if f.read(8) == b'EXFAT   ':
                    raise NotImplementedError("Detected exFAT filesystem. This script does NOT support exFAT.")

                is_raw_partition = True
        except (NotImplementedError, ValueError) as e:
            print(f"CRITICAL: {e}")
            return
        except Exception:
            # Any unpacking error means it's likely an MBR with random bootcode bytes
            is_raw_partition = False

        # ---------------------------------------------------------
        # EXECUTION PATH
        # ---------------------------------------------------------
        if is_raw_partition:
            print("Detected Raw Partition / Floppy Disk image (No partition table).")
            try:
                clean_fat_partition(f, 0)
            except (NotImplementedError, ValueError) as e:
                print(f"CRITICAL: {e}")
            except Exception as e:
                print(f"Failed to parse raw image: {e}")
            return

        # If it's not a raw partition, we safely treat it as an MBR Partition Table
        print("MBR detected (Multi-partition disk layout). Traversing partitions...")
        partition_table_offset = 446
        extended_partition_types = [0x05, 0x0F]
        fat_types = [0x01, 0x04, 0x06, 0x0B, 0x0C, 0x0E]

        for i in range(4):
            f.seek(partition_table_offset + (i * 16))
            entry = f.read(16)
            p_type = entry[4]  # Correct index for partition type
            if p_type == 0:
                continue

            start_sector = int.from_bytes(entry[8:12], "little")
            total_sectors = int.from_bytes(entry[12:16], "little")

            if p_type in extended_partition_types:
                print(f"\n[Extended Partition #{i+1}] Type: 0x{p_type:02X}, Start Sector: {start_sector}")
                try:
                    parse_logical_partitions(f, start_sector, start_sector)
                except (NotImplementedError, ValueError):
                    return

            elif p_type in fat_types:
                print(f"\n[Primary Partition #{i+1}] Type: 0x{p_type:02X}, Start Sector: {start_sector}, Total Sectors: {total_sectors}")
                try:
                    clean_fat_partition(f, start_sector)
                except (NotImplementedError, ValueError) as e:
                    print(f"CRITICAL: {e}")
                    return
                except Exception as e:
                    print(f"  [!] General error processing primary partition: {e}")
            else:
                print(f"\n[Primary Partition #{i+1}] Type: 0x{p_type:02X} -> Non-FAT partition, skipping.")

import sys
import time
print("WARNING: BACKUP YOUR IMAGE FIRST!")
for i in range(10):
    print(f"Press Ctrl + C to abort ({10-i} s)")
    time.sleep(1)
scan_and_clean_image(sys.argv[1])
