name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v3

    - name: apt get
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq git build-essential clang mingw-w64 libasound2-dev libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxv-dev --no-install-recommends

    - name: prepare
      run: scripts/build.sh thirdparty

    - name: build
      run: scripts/build.sh tiny386

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2.7
        target: esp32s3
        command: scripts/build.sh patch_idf && scripts/build.sh esp

    - name: esp-idf esp32p4 build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v6.0.2
        target: esp32p4
        command: scripts/build.sh patch_idf_60 && scripts/build.sh esp_p4

    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOADTOOL_ISPRERELEASE: "true"
      run: wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh && scripts/build.sh bundle && bash upload.sh tiny386.tar.xz
